sonar.projectKey=Notes-App
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.exclusions=**/.env,**/.env.*,**/node_modules/**,**/coverage/**,**/.scannerwork/**
